console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;console.log('my old zen');
console.log('want four more years?');
;console.log("it's all happening");
;